import "./styles/globals.css";
import Wrapper from "./components/wrapper.js";

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <Wrapper>
        <body>{children}</body>
      </Wrapper>
    </html>
  );
}
